//! Auto-generate no-op `perry_ui_*` / `perry_system_*` / `perry_updater_*`
//! FFI stubs for the harmonyos build (#395 + #399).
//!
//! HarmonyOS goes through the `perry-codegen-arkts` harvest model — the
//! `App({body: VStack([...])})` literal is destructively rewritten into
//! ArkUI source so for the harvested widget tree the LLVM codegen never
//! sees `perry_ui_*` calls. There is no `perry-ui-harmonyos` crate by
//! design.
//!
//! But three families of `perry/*` FFI helpers leak into the lowered
//! `.so`:
//!
//! - **perry/ui** (#395): library factory functions like Hone's
//!   `createEditorPerryWidget`, event-handler closure bodies,
//!   conditional widget builders — anything not part of the harvest
//!   target's `App({body: ...})` literal.
//! - **perry/system** (#399): `isDarkMode()`, `getDeviceModel()`,
//!   `keychainSave/get`, `notificationSend`, etc. — never go through
//!   the harvest pass at all (the harvest only looks at the App body),
//!   so every `perry/system` call survives into LLVM codegen.
//! - **perry/updater** (#399): `install`, `verifyHash`,
//!   `compareVersions`, etc. — same shape as perry/system.
//!
//! Without these stubs the OHOS dynamic linker rejects the .so at app
//! launch with `Error relocating ... perry_X: symbol not found` and
//! the program never reaches `main`.
//!
//! We drive the stub list off `perry-dispatch`'s four tables —
//! PERRY_UI_TABLE + PERRY_UI_INSTANCE_TABLE + PERRY_SYSTEM_TABLE +
//! PERRY_UPDATER_TABLE — the same single-source-of-truth the LLVM
//! codegen consumes — so a new dispatch row automatically gets a stub
//! and there's no whack-a-mole.
//!
//! We deliberately SKIP the i18n + media tables: `perry_i18n_*` has
//! real implementations in `crates/perry-runtime/src/i18n.rs` (always
//! compiled), and `perry_media_*` has real implementations in
//! `crates/perry-runtime/src/media_playback.rs` (gated
//! `cfg(feature = "ohos-napi")`, harmonyos-only AVPlayer drain bridge).
//! Stubbing those would cause duplicate-symbol errors at link time.
//!
//! Each stub returns the zero-value for its declared `ReturnKind`
//! (handle 0 for Widget, 0.0 for F64, no-op for Void, null pointer for
//! Str). The perry/ui call becomes a visual no-op but the app boots.
//! The harvest path's widgets render normally; only non-harvested
//! perry/ui calls degrade. Replace specific stubs with real ArkUI
//! bridges as they're needed.

use perry_dispatch::{ArgKind, MethodRow, ReturnKind};
use std::collections::HashSet;
use std::fmt::Write;

fn arg_kind_rust_type(k: ArgKind) -> &'static str {
    match k {
        ArgKind::Widget | ArgKind::I64Raw | ArgKind::Str => "i64",
        ArgKind::F64 | ArgKind::Closure => "f64",
    }
}

fn return_kind(k: ReturnKind) -> (Option<&'static str>, &'static str) {
    match k {
        ReturnKind::Widget | ReturnKind::Str | ReturnKind::I64AsF64 => (Some("i64"), "0"),
        ReturnKind::F64 => (Some("f64"), "0.0"),
        ReturnKind::Void => (None, ""),
    }
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../perry-dispatch/src/lib.rs");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = std::path::Path::new(&out_dir).join("perry_ui_harmonyos_stubs.rs");

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by perry-runtime/build.rs from perry-dispatch tables.\n");
    out.push_str("// Do not edit. See build.rs and crates/perry-dispatch/src/lib.rs.\n\n");

    // Without `ohos-napi` the platform UI crate (perry-ui-macos /
    // perry-ui-android / perry-ui-gtk4 / perry-ui-windows / perry-ui-ios
    // / etc.) defines every `perry_ui_*` symbol; defining them here too
    // would be a duplicate-symbol error. Emit an empty file so the
    // include! still resolves.
    let ohos_napi = std::env::var("CARGO_FEATURE_OHOS_NAPI").is_ok();
    if !ohos_napi {
        out.push_str("// (No content — `ohos-napi` feature not enabled.)\n");
        std::fs::write(&dest, out).expect("failed to write stub file");
        return;
    }

    let tables: &[&[MethodRow]] = &[
        perry_dispatch::PERRY_UI_TABLE,
        perry_dispatch::PERRY_UI_INSTANCE_TABLE,
        perry_dispatch::PERRY_SYSTEM_TABLE,
        perry_dispatch::PERRY_UPDATER_TABLE,
    ];

    // Symbols owned by other modules in perry-runtime — stubbing here
    // would be a duplicate-symbol error at link time. Keep this list in
    // sync with `crates/perry-runtime/src/i18n.rs` +
    // `crates/perry-runtime/src/media_playback.rs`. The `perry_i18n_` /
    // `perry_media_` prefixes don't appear in the four tables above so
    // this is belt-and-braces — the actual filter is the table list.
    fn is_stubbable(runtime: &str) -> bool {
        runtime.starts_with("perry_ui_")
            || runtime.starts_with("perry_system_")
            || runtime.starts_with("perry_updater_")
            // `perry_get_device_idiom` is the one outlier in
            // PERRY_SYSTEM_TABLE that doesn't carry a `perry_system_`
            // prefix. Allow it explicitly.
            || runtime == "perry_get_device_idiom"
    }

    let mut seen: HashSet<&str> = HashSet::new();
    let mut count = 0usize;

    for table in tables {
        for row in table.iter() {
            if !is_stubbable(row.runtime) {
                continue;
            }
            // Some dispatch rows reuse the same runtime symbol (e.g.
            // `scrollViewSetChild` and `scrollviewSetChild` both →
            // `perry_ui_scrollview_set_child`). Emit each symbol once.
            if !seen.insert(row.runtime) {
                continue;
            }

            let args: String = row
                .args
                .iter()
                .enumerate()
                .map(|(i, k)| format!("_a{}: {}", i, arg_kind_rust_type(*k)))
                .collect::<Vec<_>>()
                .join(", ");

            let (ret_ty, default) = return_kind(row.ret);

            writeln!(out, "#[no_mangle]").unwrap();
            match ret_ty {
                Some(ty) => writeln!(
                    out,
                    "pub extern \"C\" fn {}({}) -> {} {{ {} }}",
                    row.runtime, args, ty, default
                )
                .unwrap(),
                None => {
                    writeln!(out, "pub extern \"C\" fn {}({}) {{}}", row.runtime, args).unwrap()
                }
            }
            count += 1;
        }
    }

    // Direct-call FFI symbols that bypass the dispatch tables — codegen
    // emits these for the simple constructor shapes (`VStack(items)`,
    // `HStack(items)`, `Button(label, onPress)`) in
    // `crates/perry-codegen/src/lower_call/native.rs`. They aren't in
    // PERRY_UI_TABLE so the table walk above misses them; we list them
    // explicitly here. Keep in sync with the hardcoded callsites in
    // lower_call/native.rs — `grep 'perry_ui_.*_create' lower_call/native.rs`.
    let direct_call_stubs: &[(&str, &[ArgKind], ReturnKind)] = &[
        (
            "perry_ui_vstack_create",
            &[ArgKind::F64],
            ReturnKind::Widget,
        ),
        (
            "perry_ui_hstack_create",
            &[ArgKind::F64],
            ReturnKind::Widget,
        ),
        (
            "perry_ui_button_create",
            &[ArgKind::Str, ArgKind::Closure],
            ReturnKind::Widget,
        ),
    ];
    for (name, args, ret) in direct_call_stubs {
        if !seen.insert(name) {
            continue;
        }
        let args_str: String = args
            .iter()
            .enumerate()
            .map(|(i, k)| format!("_a{}: {}", i, arg_kind_rust_type(*k)))
            .collect::<Vec<_>>()
            .join(", ");
        let (ret_ty, default) = return_kind(*ret);
        writeln!(out, "#[no_mangle]").unwrap();
        match ret_ty {
            Some(ty) => writeln!(
                out,
                "pub extern \"C\" fn {}({}) -> {} {{ {} }}",
                name, args_str, ty, default
            )
            .unwrap(),
            None => writeln!(out, "pub extern \"C\" fn {}({}) {{}}", name, args_str).unwrap(),
        }
        count += 1;
    }

    writeln!(out, "\n// {} stub(s) generated.", count).unwrap();
    std::fs::write(&dest, out).expect("failed to write stub file");
}
